title: ALIEN RPG — Шпаргалка для игроков
description: Краткий справочник по правилам ALIEN RPG для быстрого доступа во время игры
markdown: kramdown
remote_theme: "jekyll/minima@93b1921"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
