title: ALIEN RPG
description: Краткий справочник по правилам ALIEN RPG для быстрого доступа во время игры
markdown: kramdown
remote_theme: just-the-docs/just-the-docs@v0.10.0
color_scheme: my-scheme
search_enabled: true
baseurl: "/alien-rpg-players-handbook"
head_scripts: "https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap"
